[config]
schemaVersion = "0.0.1"

[package]
namespace = "CoreMods"
name = "CoreLib"
description = "A library that makes modding Core Keeper easier"
websiteUrl = "https://github.com/Jrprogrammer/CoreLib"
containsNsfwContent = false

  [package.dependencies]
  BepInEx-BepInExPack_Core_Keeper = "2.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./../Build"

  [[build.copy]]
  source = "./../Staging"
  target = "./"

[publish]
repository = "core-keeper.thunderstore.io"
communities = [ "core-keeper" ]
categories = [ ]	