// ReSharper disable once CheckNamespace
namespace CoreLib.Submodule.Command
{
    /// <summary>
    /// Represents a handler for server-side commands.
    /// This interface must be implemented to define server-side commands,
    /// which are executed server-side and adhere to the permission system.
    /// Commands must be registered by invoking CommandsModule.AddCommands(modId).
    /// </summary>
    public interface IServerCommandHandler : ICommandInfo
    {
        /// <summary>
        /// Executes a command and returns the result as feedback.
        /// </summary>
        /// <param name="parameters">The arguments provided for the command.</param>
        /// <param name="sender">The entity representing the sender of the command.</param>
        /// <returns>The output generated by executing the command.</returns>
        CommandOutput Execute(string[] parameters, Unity.Entities.Entity sender);
    }
}